name: "[CI] Pipeline"
on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      NEW_VERSION: ${{ steps.semantic_release.outputs.new_release_version }}
      TAG: ${{ steps.generate_tag.outputs.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: yarn

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Generate TAG
        id: generate_tag
        run: | 
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: echo Outputs
        run: |
          echo "${{ steps.semantic_release.outputs.new_release_version }}"
          echo "${{ steps.generate_tag.outputs.sha }}"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: echo Outputs
        run: |
          echo "${{ needs.build.outputs.NEW_VERSION }}"
          echo "${{ needs.build.outputs.TAG }}"

      - name: Login Docker HUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            1renatodevops/docker-dockerhub:${{ needs.build.outputs.NEW_VERSION }} 
            1renatodevops/docker-dockerhub:${{ needs.build.outputs.TAG }}